name: calculator
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  lints: ^4.0.0
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12
  test: ^1.24.0
  